version: "2.4"
services:
  postgres:
    image: postgres:14
    container_name: db_ocp
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "${DB_PATH}"

  web-auth:
    build:
      context: .
      dockerfile: Dockerfile.dev

    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
    ports:
      - "5000:5000"
    environment:
      TZ: Europe/Warsaw
      FLASK_ENV: development
    depends_on:
      - postgres

networks:
  default:
    external:
      name: external-example
